// Generated by Wrangler by running `wrangler types`

interface Env {
  DATABASE_URL: string
  DIRECT_URL: string
  SESSION_SECRET: string
  GOOGLE_CALLBACK_BASE_URL: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
}
